#@echo off
cd C:\apps
start setup\scripts\eureka-server.bat
start setup\scripts\vehicle-service.bat
start setup\scripts\checkout-service.bat
start setup\scripts\credit-service.bat
start setup\scripts\customer-service.bat
start setup\scripts\inventory-service.bat
start setup\scripts\elasticsearch.bat
start setup\scripts\kibana.bat
